sudo: required
services:
  - docker
before_install:
  - docker build . -t bionic_ws
  - sudo apt-get update && sudo apt-get install -y sshpass
script:
  - docker run -d -p 2222:22 bionic_ws
  - sshpass -pdummyPassword ssh -o StrictHostKeyChecking=no -p2222 ubuntu@localhost echo no-op
